name: Hprofile Actions

on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Compile the project
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ https://sonarcloud.io }}
          SONAR_LOGIN: ${{ 61db700a769cc8503cebc012cf1e3965bd9dda87 }}
          SONAR_ORGANIZATION: ${{ hprofile123 }}
          SONAR_PROJECT_KEY: ${{ hprofile123 }}
        run: |
          sonar-scanner -X \
            -Dsonar.host.url=$https://sonarcloud.io \
            -Dsonar.login=$61db700a769cc8503cebc012cf1e3965bd9dda87 \
            -Dsonar.organization=$hprofile123 \
            -Dsonar.projectKey=$hprofile123 \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes
